name: Kalshi Alert

on:
  workflow_dispatch:

  schedule:
    - cron: '*/5 * * * *'

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run F1 alerts
        run: python f1_alerts.py
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

      - name: Commit updated ticker list and alert state
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add seen_tickers.json
          git add price_alert_state.json

          git diff --cached --quiet || git commit -m "Update F1 alert state"

          git push
